function range = randrange(M,m)
% random range in 1:M generated by drawing m possible boundaries from the
% uniform distribution in 1:M and choosing two consecutive ones as the
% boundaries of the generated random range.

n = max(2,ceil(M/m)) ;
r = randi(M,1,n) ;
r = sort(r) ;
i = randi(n-1) ;
range = [r(i) r(i+1)] ;

end